"""
Attachment Intelligence Engine - Risk Engine

Combines findings from multiple attachment analysis modules and
produces a normalized final risk score, severity, confidence,
and security verdict.
"""

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass, field
from typing import Any, Dict, Iterable, List, Optional


SEVERITY_WEIGHTS = {
    "CRITICAL": 1.00,
    "HIGH": 0.75,
    "MEDIUM": 0.50,
    "LOW": 0.25,
    "INFO": 0.10,
    "UNKNOWN": 0.00,
}


SEVERITY_SCORE_FLOORS = {
    "CRITICAL": 85.0,
    "HIGH": 65.0,
    "MEDIUM": 40.0,
    "LOW": 15.0,
    "INFO": 0.0,
    "UNKNOWN": 0.0,
}


VERDICT_THRESHOLDS = (
    (90.0, "Malicious"),
    (75.0, "Highly Suspicious"),
    (55.0, "Suspicious"),
    (30.0, "Potential Risk"),
    (10.0, "Low Risk"),
    (0.0, "No Significant Threat Detected"),
)


@dataclass
class RiskFinding:
    """
    Normalized finding used by the central risk engine.
    """

    rule_id: str
    title: str
    description: str
    severity: str
    score: float
    source: str = "unknown"

    evidence: Dict[str, Any] = field(
        default_factory=dict
    )

    confidence: float = 1.0

    def to_dict(self) -> Dict[str, Any]:

        return {
            "rule_id": self.rule_id,
            "title": self.title,
            "description": self.description,
            "severity": self.severity,
            "score": round(
                self.score,
                2,
            ),
            "source": self.source,
            "evidence": self.evidence,
            "confidence": round(
                self.confidence,
                2,
            ),
        }


@dataclass
class RiskEngineResult:
    """
    Final output generated by the central attachment risk engine.
    """

    score: float = 0.0

    severity: str = "UNKNOWN"

    confidence: float = 0.0

    verdict: str = (
        "Not analyzed"
    )

    risk_factors: List[str] = field(
        default_factory=list
    )

    findings: List[RiskFinding] = field(
        default_factory=list
    )

    source_scores: Dict[str, float] = field(
        default_factory=dict
    )

    statistics: Dict[str, Any] = field(
        default_factory=dict
    )

    def to_dict(self) -> Dict[str, Any]:

        return {
            "score": round(
                self.score,
                2,
            ),
            "severity": self.severity,
            "confidence": round(
                self.confidence,
                2,
            ),
            "verdict": self.verdict,
            "risk_factors": self.risk_factors,
            "findings": [
                finding.to_dict()
                for finding in self.findings
            ],
            "source_scores": {
                key: round(value, 2)
                for key, value
                in self.source_scores.items()
            },
            "statistics": self.statistics,
        }


def normalize_severity(
    severity: Optional[str],
) -> str:

    if not severity:

        return "UNKNOWN"

    normalized = str(
        severity
    ).upper().strip()

    if normalized in SEVERITY_WEIGHTS:

        return normalized

    return "UNKNOWN"


def clamp(
    value: float,
    minimum: float,
    maximum: float,
) -> float:

    return max(
        minimum,
        min(
            maximum,
            value,
        ),
    )


def calculate_severity_score(
    severity: str,
    score: float,
) -> float:

    normalized_severity = (
        normalize_severity(severity)
    )

    weight = SEVERITY_WEIGHTS[
        normalized_severity
    ]

    adjusted_score = score * (
        0.60 + (weight * 0.40)
    )

    return clamp(
        adjusted_score,
        0.0,
        100.0,
    )


def get_highest_severity(
    findings: Iterable[RiskFinding],
) -> str:

    highest = "UNKNOWN"

    highest_weight = 0.0

    for finding in findings:

        severity = normalize_severity(
            finding.severity
        )

        weight = SEVERITY_WEIGHTS[
            severity
        ]

        if weight > highest_weight:

            highest_weight = weight
            highest = severity

    return highest


def calculate_verdict(
    score: float,
) -> str:

    for threshold, verdict in (
        VERDICT_THRESHOLDS
    ):

        if score >= threshold:

            return verdict

    return (
        "No Significant Threat Detected"
    )


def deduplicate_findings(
    findings: Iterable[RiskFinding],
) -> List[RiskFinding]:

    unique = {}

    for finding in findings:

        key = (
            finding.rule_id,
            finding.source,
        )

        if key not in unique:

            unique[key] = finding

            continue

        existing = unique[key]

        if finding.score > existing.score:

            unique[key] = finding

    return list(
        unique.values()
    )


def calculate_source_scores(
    findings: Iterable[RiskFinding],
) -> Dict[str, float]:

    source_scores = defaultdict(float)

    for finding in findings:

        adjusted = (
            calculate_severity_score(
                finding.severity,
                finding.score,
            )
        )

        adjusted *= clamp(
            finding.confidence,
            0.0,
            1.0,
        )

        source_scores[
            finding.source
        ] += adjusted

    return {
        source: clamp(
            score,
            0.0,
            100.0,
        )
        for source, score
        in source_scores.items()
    }


def calculate_final_score(
    findings: Iterable[RiskFinding],
) -> float:

    findings = list(findings)

    if not findings:

        return 0.0


    weighted_scores = []


    for finding in findings:

        adjusted_score = (
            calculate_severity_score(
                finding.severity,
                finding.score,
            )
        )

        confidence = clamp(
            finding.confidence,
            0.0,
            1.0,
        )

        weighted_scores.append(
            adjusted_score * confidence
        )


    weighted_scores.sort(
        reverse=True
    )


    total = 0.0


    for index, score in enumerate(
        weighted_scores
    ):

        decay = max(
            0.35,
            1.0 - (
                index * 0.10
            ),
        )

        total += score * decay


    return clamp(
        total,
        0.0,
        100.0,
    )


def calculate_confidence(
    findings: Iterable[RiskFinding],
) -> float:

    findings = list(findings)

    if not findings:

        return 0.0


    confidences = [

        clamp(
            finding.confidence,
            0.0,
            1.0,
        )

        for finding in findings

    ]


    average_confidence = (
        sum(confidences) /
        len(confidences)
    )


    evidence_bonus = min(
        0.15,
        len(findings) * 0.02,
    )


    return clamp(
        average_confidence +
        evidence_bonus,
        0.0,
        1.0,
    )


def build_risk_factors(
    findings: Iterable[RiskFinding],
    limit: int = 10,
) -> List[str]:

    ordered = sorted(

        findings,

        key=lambda finding: (

            SEVERITY_WEIGHTS[
                normalize_severity(
                    finding.severity
                )
            ],

            finding.score,

        ),

        reverse=True,

    )


    factors = []

    seen = set()


    for finding in ordered:

        factor = finding.title.strip()


        if not factor:

            continue


        if factor in seen:

            continue


        seen.add(factor)

        factors.append(factor)


        if len(factors) >= limit:

            break


    return factors


def build_statistics(
    findings: Iterable[RiskFinding],
) -> Dict[str, Any]:

    findings = list(findings)


    severity_counts = defaultdict(int)

    source_counts = defaultdict(int)


    for finding in findings:

        severity_counts[
            normalize_severity(
                finding.severity
            )
        ] += 1


        source_counts[
            finding.source
        ] += 1


    return {

        "total_findings": len(
            findings
        ),

        "severity_counts": dict(
            severity_counts
        ),

        "source_counts": dict(
            source_counts
        ),

    }


def build_risk_result(
    findings: Iterable[RiskFinding],
) -> RiskEngineResult:

    normalized_findings = list(
        findings
    )


    normalized_findings = (
        deduplicate_findings(
            normalized_findings
        )
    )


    for finding in normalized_findings:

        finding.severity = (
            normalize_severity(
                finding.severity
            )
        )


        finding.score = clamp(

            float(finding.score),

            0.0,

            100.0,

        )


        finding.confidence = clamp(

            float(finding.confidence),

            0.0,

            1.0,

        )


    final_score = (
        calculate_final_score(
            normalized_findings
        )
    )


    highest_severity = (
        get_highest_severity(
            normalized_findings
        )
    )


    severity_floor = (
        SEVERITY_SCORE_FLOORS[
            highest_severity
        ]
    )


    final_score = max(

        final_score,

        severity_floor
        if normalized_findings
        else 0.0,

    )


    final_score = clamp(

        final_score,

        0.0,

        100.0,

    )


    confidence = (
        calculate_confidence(
            normalized_findings
        )
    )


    verdict = calculate_verdict(
        final_score
    )


    source_scores = (
        calculate_source_scores(
            normalized_findings
        )
    )


    risk_factors = (
        build_risk_factors(
            normalized_findings
        )
    )


    statistics = (
        build_statistics(
            normalized_findings
        )
    )


    return RiskEngineResult(

        score=final_score,

        severity=highest_severity,

        confidence=confidence,

        verdict=verdict,

        risk_factors=risk_factors,

        findings=normalized_findings,

        source_scores=source_scores,

        statistics=statistics,

    )


def convert_finding(
    finding: Any,
    source: str,
    default_confidence: float = 1.0,
) -> RiskFinding:

    if isinstance(
        finding,
        RiskFinding,
    ):

        return finding


    if hasattr(
        finding,
        "to_dict",
    ):

        data = finding.to_dict()

    elif isinstance(
        finding,
        dict,
    ):

        data = finding

    else:

        raise TypeError(
            "Finding must be a dictionary "
            "or object with to_dict()"
        )


    return RiskFinding(

        rule_id=str(
            data.get(
                "rule_id",
                data.get(
                    "finding_id",
                    "UNKNOWN_RULE",
                ),
            )
        ),

        title=str(
            data.get(
                "title",
                "Unknown finding",
            )
        ),

        description=str(
            data.get(
                "description",
                "",
            )
        ),

        severity=normalize_severity(
            data.get(
                "severity",
                "UNKNOWN",
            )
        ),

        score=float(
            data.get(
                "score",
                0.0,
            )
        ),

        source=source,

        evidence=data.get(
            "evidence",
            {},
        ) or {},

        confidence=float(
            data.get(
                "confidence",
                default_confidence,
            )
        ),

    )


def collect_findings(
    source: str,
    findings: Iterable[Any],
    default_confidence: float = 1.0,
) -> List[RiskFinding]:

    normalized = []


    for finding in findings:

        normalized.append(

            convert_finding(

                finding=finding,

                source=source,

                default_confidence=(
                    default_confidence
                ),

            )

        )


    return normalized


__all__ = [

    "SEVERITY_WEIGHTS",

    "SEVERITY_SCORE_FLOORS",

    "VERDICT_THRESHOLDS",

    "RiskFinding",

    "RiskEngineResult",

    "normalize_severity",

    "clamp",

    "calculate_severity_score",

    "get_highest_severity",

    "calculate_verdict",

    "deduplicate_findings",

    "calculate_source_scores",

    "calculate_final_score",

    "calculate_confidence",

    "build_risk_factors",

    "build_statistics",

    "build_risk_result",

    "convert_finding",

    "collect_findings",

]
