from __future__ import annotations

ANALYSIS_VERSION = "1.1.0"
LEDGER_VERSION = "1.1.0"
SCHEMA_VERSION = 1

MAX_ID_CHARS = 256
MAX_ENGINE_ID_CHARS = 128
MAX_VERSION_CHARS = 128
MAX_REFERENCE_COUNT = 500
MAX_DEPENDENCY_COUNT = 500
MAX_METADATA_KEYS = 128
MAX_METADATA_VALUE_CHARS = 4096

STATUS_RECORDED = "RECORDED"
STATUS_VERIFIED = "VERIFIED"
STATUS_REPLAY_READY = "REPLAY_READY"
STATUS_REPLAYED = "REPLAYED"
STATUS_MATCHED = "MATCHED"
STATUS_MISMATCHED = "MISMATCHED"
STATUS_NON_REPLAYABLE = "NON_REPLAYABLE"
STATUS_DEPENDENCY_DRIFT = "DEPENDENCY_DRIFT"
STATUS_PARTIAL = "PARTIAL"
STATUS_FAILED = "FAILED"

INTEGRITY_VALID = "VALID"
INTEGRITY_CHAIN_VALID = "CHAIN_VALID"
INTEGRITY_TAMPERED = "TAMPERED"
INTEGRITY_CONFLICT = "CONFLICT"
INTEGRITY_ORPHAN = "ORPHAN"

DETERMINISTIC = "DETERMINISTIC"
CONDITIONALLY_DETERMINISTIC = "CONDITIONALLY_DETERMINISTIC"
EXTERNAL_STATE_DEPENDENT = "EXTERNAL_STATE_DEPENDENT"
NON_DETERMINISTIC = "NON_DETERMINISTIC"
NON_REPLAYABLE = "NON_REPLAYABLE"

ALLOWED_DETERMINISM = frozenset(
    {
        DETERMINISTIC,
        CONDITIONALLY_DETERMINISTIC,
        EXTERNAL_STATE_DEPENDENT,
        NON_DETERMINISTIC,
        NON_REPLAYABLE,
    }
)

TERMINAL_REPLAY_STATES = frozenset(
    {
        STATUS_MATCHED,
        STATUS_MISMATCHED,
        STATUS_NON_REPLAYABLE,
        STATUS_DEPENDENCY_DRIFT,
        STATUS_FAILED,
    }
)

HEX_CHARS = frozenset("0123456789abcdefABCDEF")


def valid_sha256(value: str) -> bool:
    if not isinstance(value, str) or len(value) != 64:
        return False
    return all(ch in HEX_CHARS for ch in value)


def valid_identifier(value: str) -> bool:
    if not isinstance(value, str):
        return False
    value = value.strip()
    if not value:
        return False
    if len(value) > MAX_ID_CHARS:
        return False
    if "/" in value or "\\" in value or "\x00" in value:
        return False
    return True
